version: "3.0"

services:
  python:
    build: 
      context: "."
      args: 
       - conda_url=https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh
       - root_password=$root_password
       - user_name=$user_name
       - user_password=$user_password
    container_name: $container_name
    hostname: $host_name
    shm_size: $shm_size
    ports: 
      - $RDPport:3389 #RDP
      - $SSHport:22 #SSH
      - $Jupyterport:8888 #Jupyter
      - $WebAPPport:8080 #web 
    command:
      bash -c '/usr/bin/supervisord -c /etc/supervisor/supervisord.conf'
    volumes: 
      - ./workdir:/home/$user_name/Workdir/:rw
    