version: "3.0"

services:
  python:
    build: 
      context: "."
      args: 
        - python_version=$python_version
        - root_password=$root_password
        - user_name=$user_name
        - user_password=$user_password
    container_name: $container_name
    hostname: $host_name
    shm_size: $shm_size
    tty: true
    ports: 
      - $RDPport:3389
      - $SSHport:22
      - $Jupyterport:8888
      - $WebAPPport:8080
    command:
      bash -c '/usr/bin/supervisord -c /etc/supervisor/supervisord.conf'
    volumes: 
      - ./workdir:/home/$user_name/Workdir/:rw
    